### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/webcam-timelapse-setup#4]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [ ] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
We're discontinuing this as a learning resource, it'll be moved into guides.
